services:
    app:
      build: .
      ports:
      - "5005:5000"
      networks:
        - db-net
      depends_on:
        mysql: 
          condition: service_healthy
    mysql:
      image: "mysql:8"
      environment:
        MYSQL_ROOT_PASSWORD: "1234"
        MYSQL_DATABASE: "chat"
      networks:
        - db-net
      healthcheck:
        test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="1234" --silent']
        interval: 3s
        retries: 5
        start_period: 30s
networks:
    db-net: 