name: test-billing
services:
  db:
      image: "mysql:8"
      command: --init-file /data/application/init.sql
      volumes:
        - ./billingdb.sql:/data/application/init.sql
      environment:
        MYSQL_ROOT_PASSWORD: "1234"
        MYSQL_DATABASE: "billdb"
      networks:
        - db-net1
      healthcheck:
        test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="1234" --silent']
        interval: 3s
        retries: 5
        start_period: 30s
  api:
      image: billing:new 
      environment:
        - WEIGHT_PORT=8084
      ports:
        - 8089:5000
      networks:
        - db-net1
        - api-test-net
      volumes:
        - ./rates_files:/app/rates_files
        - tests-billing-logs:/billing-logs # should automatically
      depends_on:
        db:
          condition: service_healthy
volumes:
  tests-billing-logs:
    external: true
networks:
    db-net1:
    api-test-net:
      external: true
