name: weight
services:
  db:
    image: mysql:8.3
    volumes:
      - weight-database:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=weight
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  api:
    build: 
      dockerfile: Dockerfile
    container_name: weight_microservice
    ports:
      - 8085:5000
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - HOST=db
      - PORT=3306
    volumes:
      - ./in:/app/in
      - weight-logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
volumes:
  weight-database:
  weight-logs:
