name: weight
services:
  db:
    image: mysql:8.3
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=weight
      - MYSQL_USER=flaskuser
      - MYSQL_PASSWORD=1999
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  api:
    image: test-weight:latest
    ports:
      - 8084:5000
    environment:
      - DATABASE_NAME=weight
      - DATABASE_USER=flaskuser
      - DATABASE_PASSWORD=1999
      - HOST=db
      - PORT=3306
    restart: always
    volumes:
      - ./in:/app/in
      - test-weight-logs:/app/logs
    networks:
      - api-test-net
    depends_on:
      db:
        condition: service_healthy
volumes:
  test-weight-logs:
    external: true
networks:
  api-test-net:
    external: true
